### ISSUE TITLE
[Input Files does not show up in analysis]

### ISSUE THREAD

**Issue by rcbrewer** [Citrullia-SDU/Citrullia#1]
**Describe the bug**
My input .mzXML.MGX files do not show up in analysis

**To Reproduce**
1. I click on Load in the Home section 
2. I select five .mzXML.MGX files
3. Analysis page pops up
4. No files appear under Input Files (.MGX) 
5. I go to Home, and it says the files were successfully uploaded 
5. I continue to set parameters in analysis (thinking they are uploaded, just the text is missing)
6. I click Run
7. I received Could not find part of path error 'C\Users\rcbrewer\Documents\Citrullia-master\Citrullia\Debug\Externals\XTandem\Outputs
8. I create an Outputs folder in X Tandem folder 
9. I receive another error - Results files was found, but no result was read. Please check your settings and try again. 

**Expected behavior**
I expected the files to show up under Input Files (.MGX). 
I expected the files to Run and Xtandem to start. 
Please see screen shots for more info

Thanks!

![Screen Shot 2020-06-19 at 3 16 37 PM](https://user-images.githubusercontent.com/67171781/85183652-51032380-b241-11ea-9c4d-4b88696c02c7.png)
![Screen Shot 2020-06-19 at 3 17 48 PM](https://user-images.githubusercontent.com/67171781/85183653-52345080-b241-11ea-96cc-1af14250b8b8.png)
![Screen Shot 2020-06-19 at 3 18 04 PM](https://user-images.githubusercontent.com/67171781/85183655-52cce700-b241-11ea-9c5b-f2d8c1a5127e.png)
![Screen Shot 2020-06-19 at 3 18 53 PM](https://user-images.githubusercontent.com/67171781/85183657-53657d80-b241-11ea-8d66-533bf4b2212c.png)
![Screen Shot 2020-06-19 at 3 24 00 PM](https://user-images.githubusercontent.com/67171781/85183658-53657d80-b241-11ea-9e28-8773e9faec1d.png)

**Screenshots**

**Desktop (please complete the following information):**
 -Windows version: [e.g. Windows 7/10 32-bit/64-bit]
 -Download version [e.g. v1.0]

**Additional context**

**Comment by Citrullia-SDU** [comment]
Downloading and installing the Citrullia version 1.2 should fix the problem
